export const links = [
  {
    nama: "Pos Duga Air (PDA)",
    data_spasial: [
      { data: "Genangan rob", jumlah: "3" },
      { data: "Genangan banjir", jumlah: "2" },
      { data: "Histori genangan", jumlah: "4" },
      { data: "Tanggul", jumlah: "6" },
      { data: "Titik tanggul keritis", jumlah: "7" },
      { data: "Titik sungai kritis", jumlah: "4" },
      { data: "Situ", jumlah: "600" },
      { data: "Danau", jumlah: "200" },
      { data: "Embung", jumlah: "259" },
      { data: "Bendungan", jumlah: "250" },
      { data: "Bendung", jumlah: "2" },
      { data: "Fase tanam", jumlah: "2" },
    ],
  },
  {
    nama: "Pos Curah Hujan (PCH)",
    data_spasial: [
      { data: "Demnas", jumlah: "4" },
      { data: "Genangan banjir", jumlah: "1" },
      { data: "Curah hujan", jumlah: "2" },
      { data: "Tanggul", jumlah: "3" },
      { data: "Titik tanggul keritis", jumlah: "6" },
      { data: "Titik sungai kritis", jumlah: "7" },
      { data: "Situ", jumlah: "300" },
      { data: "Danau", jumlah: "100" },
      { data: "Embung", jumlah: "159" },
      { data: "Bendungan", jumlah: "50" },
      { data: "Curah hujan", jumlah: "1" },
      { data: "Fase tanam", jumlah: "1" },
    ],
  },
  {
    nama: "ARR",
    data_spasial: [
      { data: "Demnas", jumlah: "4" },
      { data: "Genangan banjir", jumlah: "1" },
      { data: "Curah hujan", jumlah: "2" },
      { data: "Tanggul", jumlah: "3" },
      { data: "Titik tanggul keritis", jumlah: "6" },
      { data: "Titik sungai kritis", jumlah: "7" },
      { data: "Situ", jumlah: "300" },
      { data: "Danau", jumlah: "100" },
      { data: "Embung", jumlah: "159" },
      { data: "Bendungan", jumlah: "50" },
      { data: "Curah hujan", jumlah: "1" },
      { data: "Fase tanam", jumlah: "1" },
    ],
  },
  {
    nama: "AWLR",
    data_spasial: [
      { data: "Demnas", jumlah: "4" },
      { data: "Genangan banjir", jumlah: "1" },
      { data: "Curah hujan", jumlah: "2" },
      { data: "Tanggul", jumlah: "3" },
      { data: "Titik tanggul keritis", jumlah: "6" },
      { data: "Titik sungai kritis", jumlah: "7" },
      { data: "Situ", jumlah: "300" },
      { data: "Danau", jumlah: "100" },
      { data: "Embung", jumlah: "159" },
      { data: "Bendungan", jumlah: "50" },
      { data: "Curah hujan", jumlah: "1" },
      { data: "Fase tanam", jumlah: "1" },
    ],
  },
];
